name: "Setup Cordova - bbasinski"
description: "Setup your GitHub Actions workflow with Apache Cordova."
inputs:
  exec:
    description: "Apache Cordova command to execute"
    required: true
author: "bbasinski"
branding:
  color: black
  icon: smartphone

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.exec }}
